# Generated by Django 6.0.1 on 2026-02-22 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "questions",
            "0002_topic_alter_option_options_alter_question_options_and_more",
        ),
        ("tests", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numerical_answer",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("marks_obtained", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ResponseOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="testattempt",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="testquestion",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="testattempt",
            constraint=models.UniqueConstraint(
                fields=("test", "user", "attempt_number"),
                name="unique_attempt_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="testquestion",
            constraint=models.UniqueConstraint(
                fields=("test", "question"), name="unique_question_per_test"
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="tests.testattempt",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="questions.question",
            ),
        ),
        migrations.AddField(
            model_name="responseoption",
            name="option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="questions.option"
            ),
        ),
        migrations.AddField(
            model_name="responseoption",
            name="response",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="selected_options",
                to="tests.response",
            ),
        ),
        migrations.AddConstraint(
            model_name="response",
            constraint=models.UniqueConstraint(
                fields=("attempt", "question"), name="unique_response_per_question"
            ),
        ),
        migrations.AddConstraint(
            model_name="responseoption",
            constraint=models.UniqueConstraint(
                fields=("response", "option"), name="unique_option_per_response"
            ),
        ),
    ]
