# Generated by Django 6.0.1 on 2026-01-24 14:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tests", "0002_testquestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestAccessSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("passcode_version", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_sessions",
                        to="tests.test",
                    ),
                ),
            ],
        ),
    ]
