# Generated by Django 6.0.1 on 2026-02-01 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("tests", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="testaccesssession",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_sessions",
                to="tests.test",
            ),
        ),
    ]
